const CARD_OFFSET_X = 75;
const BACK_CARD_OFFSET_X = 50;
const CARD_OFFSET_Y = 2.5;
const CARD_ROTATION = 0.75;
const FACE_CARD_ASPECT_RATIO = 1.4;

export {
  CARD_OFFSET_X,
  BACK_CARD_OFFSET_X,
  CARD_OFFSET_Y,
  CARD_ROTATION,
  FACE_CARD_ASPECT_RATIO,
};
